### ISSUE TITLE
Ensure bzip2 is installed

### ISSUE THREAD

**Issue by SimonMckeon** [FuzzyMistborn/ansible-role-autorestic#3]
When running this playbook on a fresh server (ubuntu jammy), it throws an error due to bzip2 not being installed. 

Could a step be added to ensure bzip2 is installed prior to running the installation steps?

```
- name: Ensure bzip2 is installed
  ansible.builtin.package:
    name: bzip2
    state: present
```

Happy to open a PR if you believe this to be useful.
